Repository newrelic/newrelic-prometheus-configurator, pull requests merged in 2023-08, with the labels that each got.

#250 chore: Update CHANGELOG format
  CONTRIBUTING.md
Labels: ci/skip-e2e, ci/skip-load-test

#252 chore: Add CHANGELOG github workflow
  .github/renovate.json5
  .github/workflows/changelog.yml
  CONTRIBUTING.md
Labels: Skip Changelog

#256 Bump configurator version
  charts/newrelic-prometheus-agent/Chart.yaml
Labels: dependencies, ci/skip-e2e, Skip Changelog
